# GitHub Repository Settings Template for Trading Platform
# This file documents recommended repository settings and configurations
# Apply these through GitHub UI: Settings > General, or via GitHub API

repository_settings:
  # Basic Settings
  general:
    name: "trader-ops"
    description: "Professional trading operations dashboard with real-time market data, TradingView integration, and automated trading capabilities"
    homepage: "https://trader-ops.example.com"
    topics:
      - "trading"
      - "finance"
      - "real-time-data"
      - "electron"
      - "fastapi"
      - "tradingview"
      - "market-data"
      - "portfolio-management"
      - "vue3"
      - "python"
      - "typescript"
    visibility: "private"  # Trading platforms should typically be private
    
  # Features
  features:
    issues: true
    projects: true
    wiki: true
    discussions: true
    
    # Advanced features
    vulnerability_alerts: true
    dependency_graph: true
    dependabot_alerts: true
    dependabot_security_updates: true
    automated_security_fixes: true
    
  # Pull Requests
  pull_requests:
    allow_merge_commit: true
    allow_squash_merge: true
    allow_rebase_merge: false  # Prefer linear history
    delete_branch_on_merge: true
    suggest_updating_pull_request_branches: true
    always_suggest_updating_branches: true
    
  # Security & Analysis
  security:
    # Code scanning
    code_scanning:
      enabled: true
      default_setup: true
      
    # Secret scanning
    secret_scanning:
      enabled: true
      push_protection: true
      
    # Dependency review
    dependency_review:
      enabled: true
      
    # Private vulnerability reporting
    private_vulnerability_reporting: true

  # Branch Protection (see branch-protection-config.yml for details)
  default_branch: "main"
  
  # Repository Rules
  merge_queue:
    enabled: false  # Can be enabled for larger teams
    
  # Collaborators & Teams
  access:
    admin_users:
      - "grimmolf"  # Repository owner
    
    # For larger teams, define team access
    teams: []
    
  # GitHub Apps & Integrations
  apps:
    recommended:
      - name: "Dependabot"
        purpose: "Automated dependency updates"
        enabled: true
        
      - name: "CodeQL"
        purpose: "Security vulnerability scanning"
        enabled: true
        
      - name: "Semantic Release"
        purpose: "Automated versioning and releases"
        enabled: true

# GitHub CLI Commands to Apply Settings
cli_setup_commands: |
  # Update repository description and topics
  gh repo edit --description "Professional trading operations dashboard with real-time market data" \
    --add-topic trading,finance,real-time-data,electron,fastapi,tradingview

  # Enable vulnerability alerts
  gh api repos/:owner/:repo \
    --method PATCH \
    --field has_vulnerability_alerts=true

  # Enable automated security fixes
  gh api repos/:owner/:repo/automated-security-fixes \
    --method PUT

  # Configure merge settings
  gh api repos/:owner/:repo \
    --method PATCH \
    --field allow_squash_merge=true \
    --field allow_merge_commit=true \
    --field allow_rebase_merge=false \
    --field delete_branch_on_merge=true

# Webhooks Configuration
webhooks:
  # Example webhook for trading system notifications
  trading_alerts:
    url: "https://your-trading-system.example.com/github-webhook"
    events:
      - "push"
      - "pull_request"
      - "deployment"
      - "deployment_status"
      - "release"
    secret: "WEBHOOK_SECRET"  # Store in repository secrets
    
  # Slack/Discord notifications (if using)
  notifications:
    url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
    events:
      - "release"
      - "deployment"
      - "issues"

# Repository Labels Configuration
labels:
  # Priority Labels
  priority:
    - name: "priority/critical"
      color: "D73A4A"
      description: "Critical issue affecting trading operations"
      
    - name: "priority/high"
      color: "FF6B6B"
      description: "High priority issue"
      
    - name: "priority/medium"
      color: "FFA726"
      description: "Medium priority issue"
      
    - name: "priority/low"
      color: "81C784"
      description: "Low priority issue"

  # Component Labels
  components:
    - name: "component/frontend"
      color: "42A5F5"
      description: "Frontend/UI related"
      
    - name: "component/backend"
      color: "AB47BC"
      description: "Backend/API related"
      
    - name: "component/trading"
      color: "4CAF50"
      description: "Trading system components"
      
    - name: "component/data"
      color: "FF9800"
      description: "Market data and real-time feeds"
      
    - name: "component/security"
      color: "F44336"
      description: "Security related"
      
    - name: "component/performance"
      color: "9C27B0"
      description: "Performance related"

  # Type Labels
  types:
    - name: "type/bug"
      color: "D73A4A"
      description: "Something isn't working"
      
    - name: "type/feature"
      color: "0E8A16"
      description: "New feature request"
      
    - name: "type/enhancement"
      color: "84B6EB"
      description: "Enhancement to existing feature"
      
    - name: "type/documentation"
      color: "D4EDDA"
      description: "Documentation changes"
      
    - name: "type/maintenance"
      color: "EDEDED"
      description: "Maintenance and housekeeping"

  # Status Labels
  status:
    - name: "status/needs-review"
      color: "FBCA04"
      description: "Awaiting review"
      
    - name: "status/in-progress"
      color: "0052CC"
      description: "Currently being worked on"
      
    - name: "status/blocked"
      color: "B60205"
      description: "Blocked by dependency"
      
    - name: "status/ready-to-merge"
      color: "0E8A16"
      description: "Ready for merge"

  # Special Labels
  special:
    - name: "auto-merge"
      color: "B4E7CE"
      description: "Safe for automated merging"
      
    - name: "breaking-change"
      color: "D73A4A"
      description: "Introduces breaking changes"
      
    - name: "dependencies"
      color: "0366D6"
      description: "Dependency updates"
      
    - name: "market-hours"
      color: "FF6B35"
      description: "Affects trading during market hours"

# Project Templates
project_templates:
  trading_sprint:
    name: "Trading Platform Sprint"
    description: "Sprint planning for trading platform development"
    columns:
      - "📋 Backlog"
      - "🔄 In Progress"
      - "👀 Review"
      - "✅ Done"
      - "🚀 Deployed"

  security_review:
    name: "Security Review Board"
    description: "Track security issues and improvements"
    columns:
      - "🔍 Identified"
      - "📊 Risk Assessment"
      - "🛠️ Mitigation"
      - "✅ Resolved"

# GitHub Discussions Categories
discussions:
  categories:
    - name: "Trading Strategies"
      description: "Discuss trading strategies and platform usage"
      emoji: "📈"
      
    - name: "Technical Support"
      description: "Get help with setup and configuration"
      emoji: "🛠️"
      
    - name: "Feature Requests"
      description: "Suggest new features and improvements"
      emoji: "💡"
      
    - name: "Market Data"
      description: "Discuss market data sources and integration"
      emoji: "📊"
      
    - name: "TradingView Integration"
      description: "TradingView specific help and customization"
      emoji: "📋"

# Automated Setup Script
setup_script: |
  #!/bin/bash
  # Run this script to configure repository settings via GitHub CLI
  
  echo "🔧 Configuring repository settings..."
  
  # Apply repository settings
  gh repo edit \
    --description "Professional trading operations dashboard with real-time market data, TradingView integration, and automated trading capabilities" \
    --add-topic trading,finance,real-time-data,electron,fastapi,tradingview,market-data,portfolio-management,vue3,python,typescript \
    --enable-issues \
    --enable-projects \
    --enable-wiki \
    --enable-discussions
  
  # Create labels
  echo "🏷️ Creating repository labels..."
  gh label create "priority/critical" --color "D73A4A" --description "Critical issue affecting trading operations" || true
  gh label create "component/trading" --color "4CAF50" --description "Trading system components" || true
  gh label create "market-hours" --color "FF6B35" --description "Affects trading during market hours" || true
  
  echo "✅ Repository configuration complete!"