# Secrets Template - DO NOT COMMIT WITH REAL VALUES
# Copy this file to 05-secrets.yaml and replace with actual values
apiVersion: v1
kind: Secret
metadata:
  name: traderterminal-secrets
  namespace: traderterminal
type: Opaque
stringData:
  # Database
  database-url: "postgresql://user:password@postgres:5432/traderterminal"
  
  # Tradovate Credentials
  tradovate-username: "your-tradovate-username"
  tradovate-password: "your-tradovate-password"
  tradovate-app-id: "your-tradovate-app-id"
  
  # TopstepX Credentials
  topstepx-api-key: "your-topstepx-api-key"
  topstepx-username: "your-topstepx-username"
  
  # TradingView Webhook Security
  webhook-secret: "your-secure-webhook-secret"
  
  # Charles Schwab OAuth
  schwab-client-id: "your-schwab-client-id"
  schwab-client-secret: "your-schwab-client-secret"
  
  # Tastytrade Credentials
  tastytrade-username: "your-tastytrade-username"
  tastytrade-password: "your-tastytrade-password"