name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-python-dependencies:
    name: Update Python Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install "3.11"

      - name: Update dependencies
        run: |
          # Update all dependencies to latest compatible versions
          uv sync --upgrade
          
          # Generate lock file
          uv lock --upgrade

      - name: Run tests to verify updates
        run: |
          uv sync --group dev
          uv run pytest tests/unit/ -x --tb=short

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update Python dependencies"
          title: "chore: update Python dependencies"
          body: |
            This PR updates Python dependencies to their latest compatible versions.
            
            ## Changes
            - Updated all Python dependencies using `uv sync --upgrade`
            - Generated new lock file with `uv lock --upgrade`
            - All tests are passing
            
            ## Testing
            - [x] Unit tests pass
            - [x] Dependencies resolve correctly
            
            **Note**: This PR was automatically generated by the dependency update workflow.
          branch: chore/update-python-dependencies
          delete-branch: true

  update-node-dependencies:
    name: Update Node.js Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'

      - name: Update dependencies
        run: |
          # Update all dependencies
          npm update
          
          # Audit and fix security vulnerabilities
          npm audit fix || true

      - name: Run tests to verify updates
        run: |
          npm ci
          npm run test:unit
          npm run build

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update Node.js dependencies"
          title: "chore: update Node.js dependencies"
          body: |
            This PR updates Node.js dependencies to their latest versions.
            
            ## Changes
            - Updated all Node.js dependencies using `npm update`
            - Fixed security vulnerabilities with `npm audit fix`
            - All tests and build are passing
            
            ## Testing
            - [x] Unit tests pass
            - [x] Build succeeds
            - [x] No new security vulnerabilities
            
            **Note**: This PR was automatically generated by the dependency update workflow.
          branch: chore/update-node-dependencies
          delete-branch: true